### ISSUE TITLE
Cant't see post list in home page

### ISSUE THREAD

**Issue by nezhazheng** [dbtek/blog#1]
Hi
  This blog is really beautiful.
  I clone this repo , and i ran jekyll serve , everything is ok, except i can't see the post list in home page.
  Could you give me any suggestion?

**Comment by dbtek** [comment]
Hi,

Thanks a lot. This can be related to jekyll version. I'm running it quite well with jekyll 1.5.1 on ruby 1.8.7.
I'm not a ruby expert. I suggest you to check the jekyll and ruby versions. Also checking logs could help you.
